run:
  timeout: 3m

linters:
  disable-all: true
  enable:
    - govet
    - gosimple
    - staticcheck
    - ineffassign
    - misspell

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
