name: Build (main)

on:
  push:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: Tidy
        run: go mod tidy
      - name: Lint (go vet)
        run: go vet ./...
      - name: Build
        run: make build
      - name: Test
        run: make test
