name: CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout=3m
      - name: Tidy
        run: go mod tidy
      - name: Lint (go vet)
        run: go vet ./...
      - name: Lint (golangci)
        run: golangci-lint run
      - name: Build
        run: make build
      - name: Test
        run: make test
